//
//  JaemIconStyleKit.swift
//  jaem
//
//  Created by limtaegeun on 2016. 4. 7..
//  Copyright (c) 2016 whataday. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class JaemIconStyleKit : NSObject {

    //// Cache

    private struct Cache {
        static var imageOfExitButton: UIImage?
        static var exitButtonTargets: [AnyObject]?
    }

    //// Drawing Methods

    public class func drawCardStackIcon() {
        //// Color Declarations
        let strokeColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)

        //// Line-+-Line-Copy-3-+-Line-Copy-4
        //// Line Drawing
        let linePath = UIBezierPath()
        linePath.moveToPoint(CGPoint(x: 1, y: 1))
        linePath.addLineToPoint(CGPoint(x: 12.82, y: 1))
        linePath.miterLimit = 4;

        linePath.lineCapStyle = .Square;

        linePath.usesEvenOddFillRule = true;

        strokeColor.setStroke()
        linePath.lineWidth = 1
        linePath.stroke()


        //// Line-Copy-3 Drawing
        let lineCopy3Path = UIBezierPath()
        lineCopy3Path.moveToPoint(CGPoint(x: 1, y: 3))
        lineCopy3Path.addLineToPoint(CGPoint(x: 12.82, y: 3))
        lineCopy3Path.miterLimit = 4;

        lineCopy3Path.lineCapStyle = .Square;

        lineCopy3Path.usesEvenOddFillRule = true;

        strokeColor.setStroke()
        lineCopy3Path.lineWidth = 1
        lineCopy3Path.stroke()


        //// Line-Copy-4 Drawing
        let lineCopy4Path = UIBezierPath()
        lineCopy4Path.moveToPoint(CGPoint(x: 1, y: 5))
        lineCopy4Path.addLineToPoint(CGPoint(x: 12.82, y: 5))
        lineCopy4Path.miterLimit = 4;

        lineCopy4Path.lineCapStyle = .Square;

        lineCopy4Path.usesEvenOddFillRule = true;

        strokeColor.setStroke()
        lineCopy4Path.lineWidth = 1
        lineCopy4Path.stroke()
    }

    public class func drawExitButton() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let fillColor = UIColor(red: 0.907, green: 0.907, blue: 0.907, alpha: 1.000)

        //// exit_black-copy
        //// Fill-16 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 9, 9)
        CGContextRotateCTM(context, -44.95 * CGFloat(M_PI) / 180)

        let fill16Path = UIBezierPath(rect: CGRect(x: -11.83, y: -0.6, width: 23.65, height: 1.2))
        fillColor.setFill()
        fill16Path.fill()

        CGContextRestoreGState(context)


        //// Fill-17 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 9, 9)
        CGContextRotateCTM(context, 44.95 * CGFloat(M_PI) / 180)

        let fill17Path = UIBezierPath(rect: CGRect(x: -11.83, y: -0.6, width: 23.65, height: 1.2))
        fillColor.setFill()
        fill17Path.fill()

        CGContextRestoreGState(context)
    }

    public class func drawAddButton() {
        //// Color Declarations
        let fillColor2 = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)

        //// plus-copy-2
        //// Fill-38 Drawing
        let fill38Path = UIBezierPath()
        fill38Path.moveToPoint(CGPoint(x: 12.5, y: 24.95))
        fill38Path.addCurveToPoint(CGPoint(x: 0.05, y: 12.5), controlPoint1: CGPoint(x: 5.64, y: 24.95), controlPoint2: CGPoint(x: 0.05, y: 19.36))
        fill38Path.addCurveToPoint(CGPoint(x: 12.5, y: 0.05), controlPoint1: CGPoint(x: 0.05, y: 5.64), controlPoint2: CGPoint(x: 5.64, y: 0.05))
        fill38Path.addCurveToPoint(CGPoint(x: 24.95, y: 12.5), controlPoint1: CGPoint(x: 19.36, y: 0.05), controlPoint2: CGPoint(x: 24.95, y: 5.64))
        fill38Path.addCurveToPoint(CGPoint(x: 12.5, y: 24.95), controlPoint1: CGPoint(x: 24.95, y: 19.36), controlPoint2: CGPoint(x: 19.36, y: 24.95))
        fill38Path.addLineToPoint(CGPoint(x: 12.5, y: 24.95))
        fill38Path.closePath()
        fill38Path.moveToPoint(CGPoint(x: 12.5, y: 1.42))
        fill38Path.addCurveToPoint(CGPoint(x: 1.42, y: 12.5), controlPoint1: CGPoint(x: 6.39, y: 1.42), controlPoint2: CGPoint(x: 1.42, y: 6.39))
        fill38Path.addCurveToPoint(CGPoint(x: 12.5, y: 23.58), controlPoint1: CGPoint(x: 1.42, y: 18.61), controlPoint2: CGPoint(x: 6.39, y: 23.58))
        fill38Path.addCurveToPoint(CGPoint(x: 23.58, y: 12.5), controlPoint1: CGPoint(x: 18.61, y: 23.58), controlPoint2: CGPoint(x: 23.58, y: 18.61))
        fill38Path.addCurveToPoint(CGPoint(x: 12.5, y: 1.42), controlPoint1: CGPoint(x: 23.58, y: 6.39), controlPoint2: CGPoint(x: 18.61, y: 1.42))
        fill38Path.addLineToPoint(CGPoint(x: 12.5, y: 1.42))
        fill38Path.closePath()
        fill38Path.miterLimit = 4;

        fill38Path.usesEvenOddFillRule = true;

        fillColor2.setFill()
        fill38Path.fill()


        //// Fill-39 Drawing
        let fill39Path = UIBezierPath(rect: CGRect(x: 5.88, y: 11.78, width: 13.25, height: 1.45))
        fillColor2.setFill()
        fill39Path.fill()


        //// Fill-40 Drawing
        let fill40Path = UIBezierPath(rect: CGRect(x: 11.78, y: 5.88, width: 1.45, height: 13.25))
        fillColor2.setFill()
        fill40Path.fill()
    }

    //// Generated Images

    public class var imageOfExitButton: UIImage {
        if Cache.imageOfExitButton != nil {
            return Cache.imageOfExitButton!
        }

        UIGraphicsBeginImageContextWithOptions(CGSize(width: 18, height: 18), false, 0)
            JaemIconStyleKit.drawExitButton()

        Cache.imageOfExitButton = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return Cache.imageOfExitButton!
    }

    //// Customization Infrastructure

    @IBOutlet var exitButtonTargets: [AnyObject]! {
        get { return Cache.exitButtonTargets }
        set {
            Cache.exitButtonTargets = newValue
            for target: AnyObject in newValue {
                target.performSelector(NSSelectorFromString("setImage:"), withObject: JaemIconStyleKit.imageOfExitButton)
            }
        }
    }

}
