//
//  JaemIconStyleKit.swift
//  jaem
//
//  Created by limtaegeun on 2016. 3. 23..
//  Copyright (c) 2016 whataday. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class JaemIconStyleKit : NSObject {

    //// Drawing Methods

    public class func drawCardStackIcon() {
        //// Color Declarations
        let strokeColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)

        //// Line-+-Line-Copy-3-+-Line-Copy-4
        //// Line Drawing
        let linePath = UIBezierPath()
        linePath.moveToPoint(CGPointMake(1, 1))
        linePath.addLineToPoint(CGPointMake(12.82, 1))
        linePath.miterLimit = 4;

        linePath.lineCapStyle = .Square;

        linePath.usesEvenOddFillRule = true;

        strokeColor.setStroke()
        linePath.lineWidth = 1
        linePath.stroke()


        //// Line-Copy-3 Drawing
        let lineCopy3Path = UIBezierPath()
        lineCopy3Path.moveToPoint(CGPointMake(1, 3))
        lineCopy3Path.addLineToPoint(CGPointMake(12.82, 3))
        lineCopy3Path.miterLimit = 4;

        lineCopy3Path.lineCapStyle = .Square;

        lineCopy3Path.usesEvenOddFillRule = true;

        strokeColor.setStroke()
        lineCopy3Path.lineWidth = 1
        lineCopy3Path.stroke()


        //// Line-Copy-4 Drawing
        let lineCopy4Path = UIBezierPath()
        lineCopy4Path.moveToPoint(CGPointMake(1, 5))
        lineCopy4Path.addLineToPoint(CGPointMake(12.82, 5))
        lineCopy4Path.miterLimit = 4;

        lineCopy4Path.lineCapStyle = .Square;

        lineCopy4Path.usesEvenOddFillRule = true;

        strokeColor.setStroke()
        lineCopy4Path.lineWidth = 1
        lineCopy4Path.stroke()
    }

}
