//
//  JaemViewStyleKit.swift
//  jaem
//
//  Created by limtaegeun on 2016. 4. 4..
//  Copyright (c) 2016 whataday. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class JaemViewStyleKit : NSObject {

    //// Drawing Methods

    public class func drawRectangle(frame frame: CGRect = CGRect(x: 0, y: 0, width: 306, height: 46)) {
        //// Color Declarations
        let strokeColor = UIColor(red: 0.530, green: 0.530, blue: 0.530, alpha: 1.000)

        //// Rectangle-15-Copy-11 Drawing
        let rectangle15Copy11Path = UIBezierPath(roundedRect: CGRect(x: frame.minX + 1, y: frame.minY + 1, width: frame.width - 2, height: frame.height - 2), cornerRadius: 10)
        strokeColor.setStroke()
        rectangle15Copy11Path.lineWidth = 1
        rectangle15Copy11Path.stroke()
    }

    public class func drawUnderLine(frame frame: CGRect = CGRect(x: 0, y: 0, width: 180, height: 39)) {
        //// Color Declarations
        let color = UIColor(red: 0.600, green: 0.600, blue: 0.600, alpha: 1.000)

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.moveToPoint(CGPoint(x: frame.maxX - 180, y: frame.maxY - 1.5))
        bezierPath.addLineToPoint(CGPoint(x: frame.maxX, y: frame.maxY - 1.5))
        bezierPath.lineCapStyle = .Round;

        color.setStroke()
        bezierPath.lineWidth = 1
        bezierPath.stroke()
    }

    //// Generated Images

    public class func imageOfUnderLine(frame frame: CGRect = CGRect(x: 0, y: 0, width: 180, height: 39)) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            JaemViewStyleKit.drawUnderLine(frame: CGRect(x: 0, y: 0, width: frame.size.width, height: frame.size.height))

        let imageOfUnderLine = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfUnderLine
    }

}
